### ISSUE TITLE
关于部分代码的理解

### ISSUE THREAD

**Issue by srtianxia** [AlexYangLi/KGCN_Keras#1]
https://github.com/AlexYangLi/KGCN_Keras/blob/1331463701e1ebee6b18b31b3d1560650fdd2fc0/models/kgcn.py#L52-L60

您好！ 感谢您使用keras复现了这篇论文的代码，我在阅读论文和代码的时候，看到了这里的双层for循环，请问这里应该如何理解呢？ 我有点没转过来这个思路，多谢！

**Comment by AlexYangLi** [comment]
你好，我的理解是，内层循环的作用是在接收邻居节点的信息然后更新自己的状态。对于item对应的entity节点来说，第一次内层循环，它接受到了它一跳内节点的信息；第二次循环，由于它的邻居节点也对各自的邻居节点的信息进行了聚合，所以接受的信息范围扩展到了2跳；第三次循环，接受的信息范围扩展了3跳。。。在代码里，外层循环执行了n_depth次，所以entity节点对n_depth跳内的信息进行了聚合。

**Comment by srtianxia** [comment]
感谢回答 我好像想明白了
